# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib SileR
#' @importFrom Rcpp evalCpp
NULL

vpowC <- function(vec1, vec2) {
    .Call('_SileR_vpowC', PACKAGE = 'SileR', vec1, vec2)
}

unboundC <- function(x) {
    .Call('_SileR_unboundC', PACKAGE = 'SileR', x)
}

#' C++ Function computing the predicted probabilities
#'
#' This function is a C++ implementation of the predictor function.
#' It is called internally by other functions.
#'
#' @param w1 The vector of the corresponding name extracted from the design matrix
#' @param b1 The vector of the corresponding name extracted from the design matrix
#' @param w2 The vector of the corresponding name extracted from the design matrix
#' @param b2 The vector of the corresponding name extracted from the design matrix
#' @param w3 The vector of the corresponding name extracted from the design matrix
#' @param w4 The vector of the corresponding name extracted from the design matrix
#' @param w5 The vector of the corresponding name extracted from the design matrix
#' @param b4 The vector of the corresponding name extracted from the design matrix
#' @param b5 The vector of the corresponding name extracted from the design matrix
#' @param age The vector of the corresponding name extracted from the data
#' @param timecap The vector of the corresponding name extracted from the data
#' @param indices_captured The vector of boolean indicated captured individuals
#'
#' @seealso \code{\link{predictor}}
#'
#' @export
predictorC <- function(w1, b1, w2, b2, w3, w4, w5, b4, b5, age, timecap, indices_captured) {
    .Call('_SileR_predictorC', PACKAGE = 'SileR', w1, b1, w2, b2, w3, w4, w5, b4, b5, age, timecap, indices_captured)
}

#' C++ Function computing the log-likelihood
#'
#' This function is a C++ implementation of \code{\link{compute_logLik}}.
#' It is called internally by other functions.
#'
#' @inheritParams parameters
#'
#' @seealso \code{\link{compute_logLik}}
#'
#' @export
compute_logLikC <- function(pred_prob, surv_bin, scale) {
    .Call('_SileR_compute_logLikC', PACKAGE = 'SileR', pred_prob, surv_bin, scale)
}

